baseURL = 'https://TimotheAlbouy.github.io/'
languageCode = 'en-us'
title = "Timothé Albouy"

[params]
	favicon = "img/favicon.png"

[[module.imports]]
path = "github.com/janraasch/hugo-bearblog"

[markup]
	[markup.goldmark]
		[markup.goldmark.renderer]
			unsafe = true
		# ref: https://gohugo.io/functions/transform/tomath/
		[markup.goldmark.extensions]
			[markup.goldmark.extensions.passthrough]
				enable = true
				[markup.goldmark.extensions.passthrough.delimiters]
					block = [['\[', '\]'], ['$$', '$$']]
					inline = [['\(', '\)'], ['$', '$']] # if '$' can be used for inline math, then non-math '$' characters must be double-escaped 